### ISSUE TITLE
使用过程遇到下面错误，如何解决

### ISSUE THREAD

**Issue by max-liulin** [1079863482/yolov5-label-xml#1]
(base) matrix@matrix-MS-7C22:~/share/src/yolov5-label-xml$ python demo.py 
5.jpg
Traceback (most recent call last):
  File "demo.py", line 71, in <module>
    img0, xyxy_list,img_crop= yolo.detect(image)       # img0检测后的图像，img_crop裁剪的图像
  File "/home/matrix/share/src/yolov5-label-xml/utils/Detect_api.py", line 66, in detect
    pred = self.model(img, augment=False)[0]
  File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/matrix/share/src/yolov5-label-xml/models/yolo.py", line 114, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/matrix/share/src/yolov5-label-xml/models/yolo.py", line 134, in forward_once
    x = m(x)  # run
  File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/matrix/share/src/yolov5-label-xml/models/common.py", line 92, in forward
    return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
  File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/matrix/share/src/yolov5-label-xml/models/common.py", line 27, in forward
    return self.act(self.bn(self.conv(x)))
  File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 438, in forward
    return F.hardswish(input, self.inplace)
  File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'

我用的是yolov5s.pt文件，什么参数都没有修改测试的。
cuda:11.0, cuda:1.7.1
是哪边配置有问题?

**Comment by 1079863482** [comment]
> (base) matrix@matrix-MS-7C22:~/share/src/yolov5-label-xml$ python demo.py
> 5.jpg
> Traceback (most recent call last):
> File "demo.py", line 71, in
> img0, xyxy_list,img_crop= yolo.detect(image) # img0检测后的图像，img_crop裁剪的图像
> File "/home/matrix/share/src/yolov5-label-xml/utils/Detect_api.py", line 66, in detect
> pred = self.model(img, augment=False)[0]
> File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/matrix/share/src/yolov5-label-xml/models/yolo.py", line 114, in forward
> return self.forward_once(x, profile) # single-scale inference, train
> File "/home/matrix/share/src/yolov5-label-xml/models/yolo.py", line 134, in forward_once
> x = m(x) # run
> File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/matrix/share/src/yolov5-label-xml/models/common.py", line 92, in forward
> return self.conv(torch.cat([x[..., ::2, ::2], x[..., 1::2, ::2], x[..., ::2, 1::2], x[..., 1::2, 1::2]], 1))
> File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/matrix/share/src/yolov5-label-xml/models/common.py", line 27, in forward
> return self.act(self.bn(self.conv(x)))
> File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 438, in forward
> return F.hardswish(input, self.inplace)
> File "/home/matrix/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in **getattr**
> raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
> torch.nn.modules.module.ModuleAttributeError: 'Hardswish' object has no attribute 'inplace'
> 
> 我用的是yolov5s.pt文件，什么参数都没有修改测试的。
> cuda:11.0, cuda:1.7.1
> 是哪边配置有问题?

这个是yolov5-v3.0版本的，需要的torch环境是pytorch1.6，你的torch版本高了

**Comment by max-liulin** [comment]
谢谢~
