### ISSUE TITLE
为什么也没有改，出现上面的报错

### ISSUE THREAD

**Issue by Maritime-Moon** [1079863482/yolov5-label-xml#2]
E:\anaconda\envs\pytorch\python.exe -X pycache_prefix=C:\Users\lenov\AppData\Local\JetBrains\PyCharmCE2024.1\cpython-cache "D:/PyCharm Community Edition 2024.1.4/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 56192 --file E:\learn_code\yolov5-label-xml-main\demo.py 
Connected to pydev debugger (build 241.18034.82)
E:\learn_code\yolov5-label-xml-main\utils\Detect_api.py:9: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.model = torch.load(model_file, map_location=self.device)['model'].float().eval()    # load FP32 model
1.jpg
Traceback (most recent call last):
  File "E:\learn_code\yolov5-label-xml-main\utils\Detect_api.py", line 68, in detect
    pred = self.model(img, augment=False)[0]
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\learn_code\yolov5-label-xml-main\models\yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "E:\learn_code\yolov5-label-xml-main\models\yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\learn_code\yolov5-label-xml-main\models\yolo.py", line 58, in forward
    self.grid[i], self.anchor_grid[i] = self._make_grid(nx, ny, i)
RuntimeError: The expanded size of the tensor (1) must match the existing size (80) at non-singleton dimension 3.  Target sizes: [1, 3, 1, 1, 2].  Tensor sizes: [3, 80, 80, 2]
python-BaseException

进程已结束，退出代码为 1

**Comment by runawayaway** [comment]
我也一样……你解决了吗

**Comment by Maritime-Moon** [comment]
这里是数据维度转换时出现错误，可以定位在self._make_grid(nx, ny, i)函数内使用view和expend的，你可以了解一下参数作用，并启用调试查看使用的变量数据维度大小，然后对参数进行替换
